[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  SECRETS_SCAN_OMIT_KEYS = ["VITE_APP_NAME", "VITE_APP_VERSION"]

[dev]
  command = "npm run dev"
  targetPort = 5173
  envFiles = [".env.local"]
