[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm run dev"
  targetPort = 5173
  envFiles = [".env.local"]
